### ISSUE TITLE
Percent symbol is cutting off text in pdf

### ISSUE THREAD

**Issue by darloth** [BlueWinds/Ex3CharmRewrite#4]
In the Charms.pdf of the original rewrite, familiar charms (or probably anything else with a percent symbol) have a single sentence's text past the percent symbol cut off.

Observe: 
http://puu.sh/vNt6g/0dcc80622a.png

http://puu.sh/vNt7a/846aebdc01.jpg

These do not match the text of the charms as written on the Onyx Path forum:
http://forum.theonyxpath.com/forum/main-category/exalted/804702-how-i-wish-charms-were-written?p=882412#post882412

so I'm pretty sure this is just a rendering-to-pdf issue, but sadly it's not one I know how to fix.

**Comment by BlueWinds** [comment]
Fixed in PR #5. Thanks for submitting. :)
